spring:
  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: lb://pssmall-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}