spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://pssmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: third_party_route
          uri: lb://pssmall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*), /$\{segment}

        - id: admin_route
          uri: lb://pssmall-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

        - id: pssmall_host_route
          uri: lb://pssmall-product
          predicates:
            - Host=localhost
